# Generated by Django 5.2.4 on 2025-07-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=255)),
                ('cache_type', models.CharField(choices=[('details', 'Details Data'), ('graph', 'Graph Data')], db_index=True, max_length=20)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('last_accessed', models.DateTimeField(auto_now=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'indexes': [models.Index(fields=['cache_key', 'cache_type'], name='myapp_persi_cache_k_a9cf09_idx'), models.Index(fields=['expires_at'], name='myapp_persi_expires_e0ecc5_idx'), models.Index(fields=['created_at'], name='myapp_persi_created_b1d925_idx')],
                'unique_together': {('cache_key', 'cache_type')},
            },
        ),
    ]
